---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-operator
  namespace: vaultwarden-operator-system
  labels:
    app.kubernetes.io/name: vaultwarden-operator
